-- Disable RLS for single-user v1 usage
ALTER TABLE settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE sku DISABLE ROW LEVEL SECURITY;
ALTER TABLE imports DISABLE ROW LEVEL SECURITY;
ALTER TABLE weekly_metrics DISABLE ROW LEVEL SECURITY;
ALTER TABLE ab_tests DISABLE ROW LEVEL SECURITY;
ALTER TABLE import_logs DISABLE ROW LEVEL SECURITY;
